### ISSUE TITLE
你看壞了吧 ｜day 4 資料夾消失了

### ISSUE THREAD

**Issue by wen-hsiu-hsu** [Rabbittee/JavaScript30#108]
# day 4 資料夾消失了

請在保留小金檔案的情況下，救回那個 day 4 資料夾

- 關連的分支 `origin/feature/day03_kim`
- 不可以直接用 main 來修正，請用 PR 來關閉這個 issue

> 花式救援的時間到了，請開始你的表演

肇事車主： @zoeGuava

**Comment by wen-hsiu-hsu** [comment]
@ashramwen 你看啦！

**Comment by haha861924** [comment]
朝聖

**Comment by ashramwen** [comment]
A_A

**Comment by alphatero** [comment]
媽！我在這！

**Comment by HuskyHsu** [comment]
> 肇事車主： @zoeGuava
![圖片 1 ](https://user-images.githubusercontent.com/18141436/149433630-3d4641a7-2f49-4117-8803-1b3f1fc48bf8.png)

**Comment by zoeGuava** [comment]
？？？？？？？乾
我不就是看個動畫而已嗎
豪......收到...

**Comment by beareatapple** [comment]
肇事逃逸？?? 還想賴小金！！
<img width="302" alt="截圖 2022-01-14 上午9 35 07" src="https://user-images.githubusercontent.com/82199955/149436447-ad752e9d-54b5-422d-9831-5223814f82bd.png">

**Comment by KimberlyYen** [comment]
### #112  復原Day04的PR <= 從這邊可以連過去

@zoeGuava 鉛筆我修了！
而且重新發了一支 PR
你看一下這樣對不對～哈囉看了也合進去了！謝謝

**Comment by alphatero** [comment]
驚！救活了

**Comment by haha861924** [comment]
小金超強

**Comment by Butterflyk77** [comment]
來看超強的小金 朝聖！

**Comment by wen-hsiu-hsu** [comment]
％％％％％
