### ISSUE TITLE
day4的第四題 我英文太爛惹

### ISSUE THREAD

**Issue by alphatero** [Rabbittee/JavaScript30#114]
How many years did all the inventors live all together
請問這個意思到底是不是說這些發明家**全部一起**共同生活了多少年？
他們沒**全部一起**共同生活過欸 還是我意思理解錯？

**Comment by wen-hsiu-hsu** [comment]
我的理解是 全部人的年紀總和 （全部人活著的時數

**Comment by alphatero** [comment]
> 我的理解是 全部人的年紀總和 （全部人活著的時數

感謝凱文 讚嘆凱文！
