### ISSUE TITLE
[ 爆雷慎入！]  Day4  No.08

### ISSUE THREAD

**Issue by KimberlyYen** [Rabbittee/JavaScript30#126]
討論：
有沒有寫了 Day04 的捧友呀～！

- 第八題：
其實這題，我看不懂 _中括弧在這邊的意思_，
解這題我是用關鍵字搜尋了`Reduce()`，在MDN裡面找到了解法，但這中括弧是啥麼？
等同於 `for` 迴圈裡面的 `[ i ]` 嗎 ？

    ```js 
    allNames[name]++
    ```
    
    附上完整的程式碼：
    ```js
    // 8. Reduce Exercise
    // Sum up the instances of each of these
    const data = [
        "car","car","truck","truck","bike","walk","car", "van","bike",  "walk",   "car","van","car","truck",
    ];
    
    const countedNames = data.reduce(function (allNames, name) {
        if (name in allNames) {
            allNames[name]++;
        } else {
            allNames[name] = 1;
        }
        return allNames;
    }, {});
    console.log(countedNames);
    ```

**Comment by ezcomenezgo** [comment]
這邊的 `allNames` 是物件，然後用 `name` 當成 key，中括號的用意是取該物件裡面的 key 去拿對應的 value 的作用
所以這邊的 `allNames[name]` 等於 `allNames.name` 的意思～

原來 `array.reduce()` 的 `acc` 可以用成物件....，謝謝小金讓我知道這件事！！！
這樣我會寫這一題了 XDDDD

**Comment by haha861924** [comment]
// data[0] = car 
當 name = car 時, allNames 這時候是空物件，還沒有 car 這個變數，所以進入 else 判斷裡 
這時候 car 數量直接記 1， 意即 allNames[car] = 1
allNames = { car: 1 }
// data[1] = car
此時 name = car，car 已經存在於 allNames 這個物件裡面，所以進入 if 第一個判斷裡面，
allNames[name]++，意即 allNames[car] = 1 + 1，所以 allNames = { car: 2}

以此類推

**Comment by KimberlyYen** [comment]
謝謝！ @haha861924 @ezcomenezgo 
### 人美心善

**Comment by haha861924** [comment]
> 這邊的 `allNames` 是物件，然後用 `name` 當成 key，中括號的用意是取該物件裡面的 key 去拿對應的 value 的作用
> 所以這邊的 `allNames[name]` 等於 `allNames.name` 的意思～
> 
> 原來 `array.reduce()` 的 `acc` 可以用成物件....，謝謝小金讓我知道這件事！！！
> 這樣我會寫這一題了 XDDDD

老師我想請問什麼是 acc

**Comment by ezcomenezgo** [comment]
> 
> 老師我想請問什麼是 acc

我是看中文的 MDN 的 `array.reduce()` 看到這個詞兒的 XD
它是 `reduce()` 的第一個參數 accumulator（累加器），然後範例在 function 裡面都簡寫成 acc
不過我剛剛看英文版的 `reduce()` 第一個參數他是用 previousValue 來表示上一個  callback 的結果
所以我猜可能要用 previousValue 來表示會比較恰當一點 XD

**Comment by HuskyHsu** [comment]
previous 或 accumulator 表示的意思還是有些不同
建議根據情境選擇用哪一個單字即可
符合意境就好，不用說一定要要用哪一個

```js
// sum
[1,2,3,4,5,6].reduce((acc, curr) => acc + curr, 0)

// max
[1,2,3,4,5,6, 4].reduce((pre, curr) => curr > pre ? curr : pre)
```

**Comment by KimberlyYen** [comment]
> 老師我想請問什麼是 acc
## 課外補充
吠～我有看這支影片給你參考
- [ Reduce() Youtube教學影片介紹 ](https://www.youtube.com/watch?v=g1C40tDP0Bk)

- 我覺得了解他原本的需求
所以簡化出來Reduce ( ) 比較好懂，但還是蠻難的 XD !
![E8F6D4DE-AA7C-4FB0-83BB-2175D3FFF2DC_4_5005_c](https://user-images.githubusercontent.com/87320011/149648339-0fe97277-e493-42f6-bdd5-d16f0406b197.jpeg)

---
- MDN 特別需要看的段落：   

![9CCBF55B-D98A-4EB2-BB57-59A66DC44B2B](https://user-images.githubusercontent.com/87320011/149648228-65441c53-b3b1-4925-a673-1679a955cf58.jpeg)

**Comment by haha861924** [comment]
原來中文版跟英文版的 MDN 還有差別 ( 受到驚嚇
蟹蟹哈奇精闢解說 武哥及小金的補充

**Comment by KimberlyYen** [comment]
> ```js
> car
> ```

吠吠 謝謝 我剛剛又重看了一次！感恩你 ❤️
