### ISSUE TITLE
預覽branch成果

### ISSUE THREAD

**Issue by HuskyHsu** [Rabbittee/JavaScript30#139]
hi
我把github page 吃的 branch 從 `main` 轉到 `gh-pages`
並且加入 github action 只要有PR就會merge 該分支到 `gh-pages` 去

所以之後發ＰＲ後，自行輸入相對路徑就可以拿到成果
方便做更改

**Comment by KimberlyYen** [comment]
> 記得vercel應該也可以做到，但我沒有研究 先提供codesandbox的手動解法
> 
> 1. [Import branch URL from GitHub](https://codesandbox.io/s/github)
>    ex. https://github.com/Rabbittee/JavaScript30/tree/feature/day04-erica
> 2. 取得連結
>    https://codesandbox.io/s/github/Rabbittee/JavaScript30/tree/feature/day04-erica?file=/day04/erica/index.html
> 3. 取得右側base網址，然後補上index.html路徑
>    ex. day04/erica/index.html
>    ![image](https://user-images.githubusercontent.com/18141436/149659293-d4cd7ea4-4a43-4fc9-bfee-8ac45f5e2d42.png)
> 
> ### GET LINK
> https://46448.csb.app/day04/erica/index.html

### 大感謝！哈奇！    
這個的方便許多！不用一個一個貼，   
目前的 Merge 預覽結果也真的自動產生了 Link 
66666真的很厲害！

**Comment by HuskyHsu** [comment]
好像有點順序上的bug，我先改回用main分支做github page

**Comment by HuskyHsu** [comment]
修好拉～～
之後發ＰＲ或是ＰＲ有更新
https://rabbittee.github.io/JavaScript30/day06/
就可以去當天那邊取得預覽
