### ISSUE TITLE
你知道 boom 是什麼嗎？

### ISSUE THREAD

**Issue by zoeGuava** [Rabbittee/JavaScript30#14]
https://github.com/Rabbittee/JavaScript30/blob/6296af685ff88c09e9068fb5a53ed17d7b3bb5c5/day01/recoil/index.html#L52

**Comment by zoeGuava** [comment]
自己去看圈圈的 pr

**Comment by lee926427** [comment]
官方長期不推薦
[KeyboardEvent.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)

**Comment by wen-hsiu-hsu** [comment]
鉛筆你好奇怪
