### ISSUE TITLE
serve (vercel 出品)

### ISSUE THREAD

**Issue by ashramwen** [Rabbittee/JavaScript30#18]
https://github.com/vercel/serve

用來跑靜態檔案來建立 web host

### usage
```sh
serve
```
```sh
# 指定目錄
server [folder_name]
```

**Comment by alphatero** [comment]
我之前有看過哈囉在github CI/CD(?) 有放跑vercel 可以直接預覽pr的branch 是不是可以參考？
https://vercel.com/docs/concepts/git/vercel-for-github

**Comment by ashramwen** [comment]
> 我之前有看過哈囉在github CI/CD(?) 有放跑vercel 可以直接預覽pr的branch 是不是可以參考？ https://vercel.com/docs/concepts/git/vercel-for-github

那要指定 branch name，而且 organization 要付錢，我沒付，阿法贊助就可以
用 `serve` 單機跑就可以看結果了，昨天我有教過圈圈，詳細你可以問問他

**Comment by alphatero** [comment]
@elzuoc 圈圈教我 我窮～
