### ISSUE TITLE
KeyboardEvent.keyCode is no longer recommended.

### ISSUE THREAD

**Issue by ericacadu** [Rabbittee/JavaScript30#21]
Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by alphatero** [comment]
的確是，vscode已經會顯示
![截圖 2022-01-05 上午8 48 41](https://user-images.githubusercontent.com/46735230/148143364-e31a192d-2eae-4aa7-b4f6-4bed90c11f8e.png)

**Comment by KimberlyYen** [comment]
!! 我也才正想發問，為什麼 keycode 被刪除線

**Comment by wen-hsiu-hsu** [comment]
這邊找到相關資料
- [StackOverflow - Char to KeyCode](https://stackoverflow.com/a/53921834/14868727)
- 上面 stackoverflow 回覆的樓下的 [有趣網頁](https://keyjs.dev/#keyboard-events-inspector)
- [MDN - charCodeAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt)
- [告别JS keyCode](https://www.zhangxinxu.com/wordpress/2021/01/js-keycode-deprecated/)

**Comment by lee926427** [comment]
我用[KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code)
keyboardEvent.code帶有值，例如:KeyA
如果還是不清楚可以到官方下圖的區塊測試
![image](https://user-images.githubusercontent.com/40841221/148183340-b9f56d55-f259-493f-810f-7f79eb96d76d.png)

**Comment by elzuoc** [comment]
可是我的keyCode在VScode沒有刪除線
![image](https://user-images.githubusercontent.com/68758083/148183059-9d315a0f-3c33-4e15-9a99-2e5b84726b8a.png)

**Comment by wen-hsiu-hsu** [comment]
> 可是我的keyCode在VScode沒有刪除線 ![image](https://user-images.githubusercontent.com/68758083/148183059-9d315a0f-3c33-4e15-9a99-2e5b84726b8a.png)

其實我的也沒有XD

**Comment by alphatero** [comment]
> 

請問你這樣不會改到題目嗎？你第一次的提交直接把data-key改掉了哎

**Comment by alphatero** [comment]
> 我用[KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) keyboardEvent.code帶有值，例如:KeyA 如果還是不清楚可以到官方下圖的區塊測試 ![image](https://user-images.githubusercontent.com/40841221/148183340-b9f56d55-f259-493f-810f-7f79eb96d76d.png)

請問你這樣不會改到題目嗎？你第一次的提交直接把data-key改掉了哎

**Comment by lee926427** [comment]
官方都說keyCode是不推薦的當然只能改data-key
原本題目的data-key看起像magic number?我個人判斷改code的方法確實有意義
以上是小弟看法

**Comment by alphatero** [comment]
> 官方都說keyCode是不推薦的當然只能改data-key 原本題目的data-key看起像magic number�?我個人判斷改code的方法確實有意義 以上是小弟看法

改了會運用到的資料不算解法，解法是你去作者github上開issue跟他說：哇靠你這是幾百年前的用法人家都沒在用了好嗎！然後發更改pr給他，然後說：看！這樣不就好了有多難？
以上是妹子我的看法

**Comment by KimberlyYen** [comment]
![B819FB4F-B328-453C-BE06-6FE0FC08E0D3_4_5005_c](https://user-images.githubusercontent.com/87320011/148187446-2e87d8a1-e853-494a-9ee9-aa4cf2a5c43e.jpeg)

我的刪除線

**Comment by lee926427** [comment]
所以技術才要迭代更新不是嗎？

**Comment by elzuoc** [comment]
既然題目在那，就如同客戶需求已定
若技術上合理且可行，也許試著換個方式解決，而非修改客戶需求
合理的限制也可以使人強大阿阿阿阿~~~~

當然實務面有足夠能力，可以說服客戶在既定預算內更改需求也未嘗不可
不過js30就是個自我挑戰的歷程嘛~
若已具備原有解題技巧，這時想修改題目加快解題速度也無可厚非 😳

不過我也真的想看看大家在限制內會如何突破找到解法~
常常讓我大開眼界~

**Comment by haha861924** [comment]
> 這邊找到相關資料
> 
> * [StackOverflow - Char to KeyCode](https://stackoverflow.com/a/53921834/14868727)
> * 上面 stackoverflow 回覆的樓下的 [有趣網頁](https://keyjs.dev/#keyboard-events-inspector)
> * [MDN - charCodeAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt)
> * [告别JS keyCode](https://www.zhangxinxu.com/wordpress/2021/01/js-keycode-deprecated/)

凱文的有趣網頁真的好可愛哦 少女心噴發

**Comment by ashramwen** [comment]
> 可是我的keyCode在VScode沒有刪除線 ![image](https://user-images.githubusercontent.com/68758083/148183059-9d315a0f-3c33-4e15-9a99-2e5b84726b8a.png)

那是因為你沒有讓 vscode 取得 event 的 type
加上 jsdoc 註解就有了
![image](https://user-images.githubusercontent.com/3334950/148194913-810be4d6-bdf2-4400-b3a7-63c09a9da9b6.png)

**Comment by alphatero** [comment]
https://github.com/Rabbittee/JavaScript30/pull/2/commits/8df9c811179d9d75f7a2a0f5f67a19d85334a68d
@haha861924  吠吠讚！

**Comment by elzuoc** [comment]
> > 可是我的keyCode在VScode沒有刪除線 ![image](https://user-images.githubusercontent.com/68758083/148183059-9d315a0f-3c33-4e15-9a99-2e5b84726b8a.png)
> 
> 那是因為你沒有讓 vscode 取得 event 的 type 加上 jsdoc 註解就有了 ![image](https://user-images.githubusercontent.com/3334950/148194913-810be4d6-bdf2-4400-b3a7-63c09a9da9b6.png)

!!! 好神奇!

**Comment by lee926427** [comment]
> > 我用[KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) keyboardEvent.code帶有值，例如:KeyA 如果還是不清楚可以到官方下圖的區塊測試 ![image](https://user-images.githubusercontent.com/40841221/148183340-b9f56d55-f259-493f-810f-7f79eb96d76d.png)
> 
> 
> 
> 請問你這樣不會改到題目嗎？你第一次的提交直接把data-key改掉了哎

我一開始看官方說不推薦就直接改掉了

**Comment by ashramwen** [comment]
> > > 可是我的keyCode在VScode沒有刪除線 ![image](https://user-images.githubusercontent.com/68758083/148183059-9d315a0f-3c33-4e15-9a99-2e5b84726b8a.png)
> > 
> > 
> > 那是因為你沒有讓 vscode 取得 event 的 type 加上 jsdoc 註解就有了 ![image](https://user-images.githubusercontent.com/3334950/148194913-810be4d6-bdf2-4400-b3a7-63c09a9da9b6.png)
> 
> !!! 好神奇!

或是不要註解，這樣寫也會有，重點就是讓 vscode 可以取得 type
![image](https://user-images.githubusercontent.com/3334950/148198605-6660f672-910c-49d7-b4a9-c996ce246dcf.png)

**Comment by elzuoc** [comment]
> 

喔真的欸!!!!!!!!!!!!!!!!!!!! 
原來要寫在 addEventListener 裡面才有

**Comment by ezcomenezgo** [comment]
等等！！原來官方不推薦！！我回家再來改 QQQ

**Comment by ezcomenezgo** [comment]
> > 
> 
> 喔真的欸!!!!!!!!!!!!!!!!!!!! 原來要寫在 addEventListener 裡面才有

但素我的 addEventListener 裡面沒有耶 @@ 都洗碟
<img width="450" alt="截圖 2022-01-05 下午7 51 39" src="https://user-images.githubusercontent.com/75515395/148213352-01b53a72-5d8e-4226-8c2f-427eb6204648.png">

**Comment by ashramwen** [comment]
> > > 
> > 
> > 
> > 喔真的欸!!!!!!!!!!!!!!!!!!!! 原來要寫在 addEventListener 裡面才有
> 
> 但素我的 addEventListener 裡面沒有耶 @@ 都洗碟 <img alt="截圖 2022-01-05 下午7 51 39" width="450" src="https://user-images.githubusercontent.com/75515395/148213352-01b53a72-5d8e-4226-8c2f-427eb6204648.png">

笑死
你的也是山寨 vscode
你滑鼠移到 e 上面看有沒有 type

**Comment by ezcomenezgo** [comment]
醬是有 type 嗎～～
不過我晚點回家去裝凱文給的套件素素看

<img width="525" alt="截圖 2022-01-05 下午8 49 42" src="https://user-images.githubusercontent.com/75515395/148220488-09b8de1d-4fc5-4d94-9968-d3df0eaa80e0.png">

**Comment by ashramwen** [comment]
> 醬是有 type 嗎～～ 不過我晚點回家去裝凱文給的套件素素看
> 
> <img alt="截圖 2022-01-05 下午8 49 42" width="525" src="https://user-images.githubusercontent.com/75515395/148220488-09b8de1d-4fc5-4d94-9968-d3df0eaa80e0.png">

XD 對
