### ISSUE TITLE
活躍排行榜計分規則

### ISSUE THREAD

**Issue by HuskyHsu** [Rabbittee/JavaScript30#27]
|  行為  |  點數  |  單位  |
|---|:---:|:---:|
| 上傳作業 | 10  |  day  |
| 連續上傳<br><sub>(ex. 連三日為 10 20 30，共 60)</sub> | base+10<br><sub>(七天後reset回1倍)</sub>  | day  |
| PR 討論 | 3 | 1 comment |
| 新的issue討論 | 8 | 1 issue |
| 被assign issue後<br>成功解決並close | 4 | 1 issue |
| 回答問題並被大家點讚<br>達4個表情符號或回應 | 10 |  1 comment |
| 為repo建立任何自動化或小工具或統計畫面 | 200 |  1 task |
| ~講一次 \凱文超強/~ | ~1~ | ~1 comment~ |

誰要練習用github action 來處理事件?

**Comment by alphatero** [comment]
舉手？

**Comment by HuskyHsu** [comment]
要練習github action者開issue做紀錄做規劃

**Comment by haha861924** [comment]
我好興奮阿

**Comment by alphatero** [comment]
請問做記錄規劃是指學習記錄及規劃？

**Comment by HuskyHsu** [comment]
喔喔
例如描述一下要怎麼做可以達到當pr被合後可以幫那個人＋10分
分數紀錄的結構想要長怎樣之類的，就是寫一個簡易的spec出來

**Comment by wen-hsiu-hsu** [comment]
我好興奮啊!
