### ISSUE TITLE
Skip no.6 on day 04

### ISSUE THREAD

**Issue by ashramwen** [Rabbittee/JavaScript30#28]
> 6. create a list of Boulevards in Paris that contain 'de' anywhere in the name
> https://en.wikipedia.org/wiki/Category:Boulevards_in_Paris
Skip it.

@Rabbittee/dunnojs

**Comment by haha861924** [comment]
收到!

**Comment by KimberlyYen** [comment]
Thanks a lot !

**Comment by KimberlyYen** [comment]
題目說明 day04 no.7：

吠之提問
> day04 no.7 他只說了 Sort the people alphabetically by last name
> 可是我看他既不是按照字母長度 也不是按照 a-z 或者 z-a 排 
![unknown](https://user-images.githubusercontent.com/87320011/149098427-e578a500-83e5-4b2a-a30b-674222f1f35a.png)

哈大之解答：
> alphabete 就是 a -> z
>  lastname 就是 第二個
> 姓氏

![D89DAB28-6C2A-4569-A4E1-AA5DDFB29EE4](https://user-images.githubusercontent.com/87320011/149105127-42a0c66b-929f-4836-832f-68de88ba66c4.jpeg)

**Comment by lee926427** [comment]
從名字的第三個字母觀察了一下，他是按照'名字'去排的?

**Comment by haha861924** [comment]
> 題目說明 day04 no.7：
> 
> 吠之提問
> 
> > day04 no.7 他只說了 Sort the people alphabetically by last name
> > 可是我看他既不是按照字母長度 也不是按照 a-z 或者 z-a 排
> > ![unknown](https://user-images.githubusercontent.com/87320011/149098427-e578a500-83e5-4b2a-a30b-674222f1f35a.png)
> 
> 哈大之解答：
> 
> > alphabete 就是 a -> z
> > lastname 就是 第二個
> > 姓氏

ㄅ歉 我是英文盲

**Comment by KimberlyYen** [comment]
### 我補圖了！！！我貼上了 
> 卡比哈囉Kayac的答案

大家可以照這個結果的方向去嘗試：
1. 用[, ]後面的文字串
2. 去排序A to Z

**Comment by KimberlyYen** [comment]
> ㄅ歉 我是英文盲

我也看不懂影片的意思，補上哈囉的解答，可以朝這方向試試
我覺得影片用錯了 
![92DBCEB3-9162-4FBC-AF42-D5D0B549FC74_4_5005_c](https://user-images.githubusercontent.com/87320011/149108878-c0e5665c-16ad-4d80-b86c-16ef05442be8.jpeg)

**Comment by wen-hsiu-hsu** [comment]
> > ㄅ歉 我是英文盲
> 
> 我也看不懂影片的意思，補上哈囉的解答，可以朝這方向試試 我覺得影片用錯了 ![92DBCEB3-9162-4FBC-AF42-D5D0B549FC74_4_5005_c](https://user-images.githubusercontent.com/87320011/149108878-c0e5665c-16ad-4d80-b86c-16ef05442be8.jpeg)

這是影片的截圖嗎 XD
Last、First 居然寫反，我以為只有我會搞錯，想不到外國人自己也會搞錯

**Comment by KimberlyYen** [comment]
### 等一下！居然！**[，]** 有差！

但我覺得，第七題的重點是：
`Sort`
`Split`
那我看的重點，會放在這兩個上面。
~~等一下！是我嗎XD~~

![32CB8603-C23D-4229-882D-A2D8D2CB12C1](https://user-images.githubusercontent.com/87320011/149111460-c7961cac-1fa6-4d53-84be-602ba29ee784.jpeg)

**Comment by lee926427** [comment]
突破盲腸了！

**Comment by ashramwen** [comment]
> > > ㄅ歉 我是英文盲
> > 
> > 
> > 我也看不懂影片的意思，補上哈囉的解答，可以朝這方向試試 我覺得影片用錯了 ![92DBCEB3-9162-4FBC-AF42-D5D0B549FC74_4_5005_c](https://user-images.githubusercontent.com/87320011/149108878-c0e5665c-16ad-4d80-b86c-16ef05442be8.jpeg)
> 
> 這是影片的截圖嗎 XD Last、First 居然寫反，我以為只有我會搞錯，想不到外國人自己也會搞錯

不... 是你搞錯 XD
有逗號跟沒逗號會相反
不過 no.7 不要在這串討論啊

**Comment by wen-hsiu-hsu** [comment]
> > > > ㄅ歉 我是英文盲
> > > 
> > > 
> > > 我也看不懂影片的意思，補上哈囉的解答，可以朝這方向試試 我覺得影片用錯了 ![92DBCEB3-9162-4FBC-AF42-D5D0B549FC74_4_5005_c](https://user-images.githubusercontent.com/87320011/149108878-c0e5665c-16ad-4d80-b86c-16ef05442be8.jpeg)
> > 
> > 
> > 這是影片的截圖嗎 XD Last、First 居然寫反，我以為只有我會搞錯，想不到外國人自己也會搞錯
> 
> 不... 是你搞錯 XD 有逗號跟沒逗號會相反 不過 no.7 不要在這串討論啊

是我太淺了...完全不知道有這回事
謝可樂大，用 JS 學英文
[參考 還不來看看](https://www.quora.com/Why-do-we-sometimes-write-the-last-name-first-with-a-comma)

~~還在討論 XDD~~

**Comment by KimberlyYen** [comment]
> 不過 no.7 不要在這串討論啊

~~XDD 我中間有想到這件事！🤪這討論串不對啊~~

**Comment by ashramwen** [comment]
Moved to #97.
