### ISSUE TITLE
no.7 on day 04: Sort the people alphabetically by last name

### ISSUE THREAD

**Issue by haha861924** [Rabbittee/JavaScript30#29]
題意: 請按字母順序排序第二個名字

![image](https://user-images.githubusercontent.com/40877568/148163150-82f7c345-7b79-46da-85c6-f9dbda862718.png)

`
const test = [  "Berne, Eric", "Berra, Yogi", "Birrell, Augustine" ] 
` <br>
輸出結果應該是 ` [  "Birrell, Augustine", "Berne, Eric", "Berra, Yogi" ]` 
**按照字母排序** Augustine ( A ) -> Eric ( E ) -> Yogi ( Y )

題目的做法看起來不是由 A-Z，也不是 Z-A，我不太清楚他的排序準則

**Comment by KimberlyYen** [comment]
謝謝吠吠！從影片看懂題目，真的會卡

**Comment by haha861924** [comment]
抱歉 我是英文盲
Bethea Erin
原來 Bethea  叫做 last name
