### ISSUE TITLE
不僅貌似忠良的男子不可相信， setInterval 提供的時間也不可信

### ISSUE THREAD

**Issue by KimberlyYen** [Rabbittee/JavaScript30#32]
我看到這篇文章，但我覺得我暫時也沒辦法。

[談談 JavaScript 的 setTimeout 與 setInterval](https://kuro.tw/posts/2019/02/23/%E8%AB%87%E8%AB%87-JavaScript-%E7%9A%84-setTimeout-%E8%88%87-setInterval/)

> 精準校時？
> 先說結論，別傻了孩子，不管你怎麼對 setTimeout() 或 setInterval() 做優化，誤差永遠都會存在。 但好消息是我們可以透過一些手法來降低誤差，像是一開始就先計算 client 的時間與 server 端的時間差，並定期與 server 端做時間同步修正，使誤差維持在最小可接受範圍內等。
> 
> 如果是要執行動畫，則建議用[ requestAnimationFrame ](https://developer.mozilla.org/zh-TW/docs/Web/API/window/requestAnimationFrame)來取代

**Comment by haha861924** [comment]
沒有錯
事實上 setimeout 跟 setinterval 的時間並不是真的那麼精準

**Comment by KimberlyYen** [comment]
` requestAnimationFrame `
有點複雜...

**Comment by haha861924** [comment]
requestAnimationFrame > setinterval  > setimeout 
之前有看到人家推薦的使用順序是這樣
不過 requestAnimationFrame  好像要動畫才會用到，所以我實務上還是使用  setinterval   居多

**Comment by wen-hsiu-hsu** [comment]
看了標題進來之後發現是在討論程式的我: 
![](https://media0.giphy.com/media/bzOwkffoJcEXcP2OxW/giphy.gif?cid=ecf05e474m7gtkj2uqt802eglj2cfsv9x2we3lwar9r2krsw&rid=giphy.gif&ct=g)

**Comment by ashramwen** [comment]
貌似忠良的小白也...

**Comment by beareatapple** [comment]
> 貌似忠良的小白也...

可以相信！！！

**Comment by kayac-chang** [comment]
> > 貌似忠良的小白也...
> 
> 
> 
> 可以相信！！！

Issue 不可以騙人
