### ISSUE TITLE
我們一直卡的 GIt，遊戲練習區

### ISSUE THREAD

**Issue by KimberlyYen** [Rabbittee/JavaScript30#64]
凱文謝謝：
謝謝以前的凱文寫的文章，
可以用這個來練習Git.

https://learngitbranching.js.org/?locale=zh_TW

**Comment by wen-hsiu-hsu** [comment]
甚麼文章啦XD
不過我覺得這個真的齁勝喔!

**Comment by KimberlyYen** [comment]
剛好看到你以前的部落格文章 😝

**Comment by wen-hsiu-hsu** [comment]
> 剛好看到你以前的部落格文章 😝

害羞

**Comment by ezcomenezgo** [comment]
這裡有一個 git 的 playground～
大家也可以玩抗抗
https://git-school.github.io/visualizing-git/

**Comment by zoeGuava** [comment]
收到...感謝 mentor 的用心...

**Comment by elzuoc** [comment]
為什麼阿金有關卡，我沒有

**Comment by elzuoc** [comment]
這遊戲好像比我笨，連 git status 都不知道欸
這怎麼玩

![image](https://user-images.githubusercontent.com/68758083/149524532-977ac173-6b21-495f-b5a0-2b6c7c6af182.png)

**Comment by elzuoc** [comment]
I don't know what mission I need to do ...

**Comment by elzuoc** [comment]
> 凱文謝謝： 謝謝以前的凱文寫的文章， 可以用這個來練習Git.
> 
> https://learngitbranching.js.org/?locale=zh_TW

原來是這個遊戲!!!!!!!!
