### ISSUE TITLE
Fake images API

### ISSUE THREAD

**Issue by HuskyHsu** [Rabbittee/JavaScript30#92]
### 最多人用的
https://picsum.photos/
![](https://picsum.photos/id/1059/400/300)

### 喵喵的，但是圖片好像是固定同一張
https://placekitten.com/
![](https://placekitten.com/400/300)

### 素色標示大小
https://placeholder.com/
![](https://via.placeholder.com/400x300)

### 同上類型
https://fakeimg.pl/
![](https://fakeimg.pl/400x300)

**Comment by zoeGuava** [comment]
補兩個之前存的～
drive 那個是簡報，裡面列了二十個免費圖庫

https://unsplash.com/developers
https://drive.google.com/file/d/18i2FrPasQ5Xil9h8Of28e1egPjsox4xq/view

**Comment by KimberlyYen** [comment]
> 喵喵的，但是圖片好像是固定同一張

救命！貓貓好可愛～ 融化了 ☺️

**Comment by HuskyHsu** [comment]
> drive 那個是簡報，裡面列了二十個免費圖庫

需求是要能夠自訂拿到的圖片大小....不是圖庫XD

**Comment by HuskyHsu** [comment]
既然前輩都提到圖庫了，就免費放送一下
https://unsplash.com/
https://visualhunt.com/
https://burst.shopify.com/
https://skitterphoto.com/
https://pixabay.com/
https://wunderstock.com/
https://www.pexels.com/zh-tw/
https://www.hippopx.com/
https://www.pickpik.com/
https://foter.com/
https://picjumbo.com/
https://xframe.io/
https://pxhere.com/
https://www.piqsels.com/
https://gratisography.com/
http://www.bara-art.com/
https://www.photo-ac.com/tw/
https://model-foto.jp/
https://www.photock.jp/

**Comment by HuskyHsu** [comment]
真要用這些圖庫做自動size可以透過images.weserv.nl
詳細請參閱
https://images.weserv.nl/docs/fit.html#cover

**Comment by KimberlyYen** [comment]
> 既然前輩都提到圖庫了，就免費放送一下 https://unsplash.com/ https://visualhunt.com/ https://burst.shopify.com/ https://skitterphoto.com/ https://pixabay.com/ https://wunderstock.com/ https://www.pexels.com/zh-tw/ https://www.hippopx.com/ https://www.pickpik.com/ https://foter.com/ https://picjumbo.com/ https://xframe.io/ https://pxhere.com/ https://www.piqsels.com/ https://gratisography.com/ http://www.bara-art.com/ https://www.photo-ac.com/tw/ https://model-foto.jp/ https://www.photock.jp/

這太值得放在issue了吧！讚
